# Inheritance

In [1]:
#problem1
class Calculation:
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def addition(self):
        print(self.x+self.y)
    def subtraction(self):
        print(self.x-self.y)
        
class MyCalculation(Calculation):
    def __init__(self,x,y):
        super().__init__(x,y)
    def multiplication(self):
        print(self.x*self.y)
    def division(self):
        print(self.x/self.y)

calc_1=MyCalculation(3,5)
calc_1.addition()
calc_1.subtraction()
calc_1.multiplication()
calc_1.division()

8
-2
15
0.6


In [2]:
#problem2
class My_Time:
    def __init__(self, t):
        self.t=t
    def printTime(self):
        print("The current time is ",self.t)

class My_Date:
    def __init__(self,d):
        self.d=d
    def printDate(self):
        print("The current date is ", self.d)

class Date_Time(My_Time, My_Date):
    def __init__(self,t,d):
        My_Time.__init__(self,t)
        My_Date.__init__(self,d)
        
dt_1=Date_Time("12 PM", "13.03.2013")
dt_1.printTime()
dt_1.printDate()

The current time is  12 PM
The current date is  13.03.2013


# Numpy

In [3]:
import numpy as np

In [4]:
#problem3
array_1=np.random.randint(1,10,(3,5))
array_1

array([[2, 9, 8, 1, 5],
       [4, 7, 8, 9, 5],
       [6, 8, 7, 8, 2]])

In [5]:
#problem4
array_2=np.zeros(10, dtype=int)
array_2[4]=3
array_2

array([0, 0, 0, 0, 3, 0, 0, 0, 0, 0])

In [6]:
#problem5
array_3=np.arange(3,16)
array_3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
#problem6
array_4=np.array([1, 3, 5, 2, 4, 5])
print(array_4.reshape(3,2),"\n")
print(array_4.reshape(2,3))
array_4

[[1 3]
 [5 2]
 [4 5]] 

[[1 3 5]
 [2 4 5]]


array([1, 3, 5, 2, 4, 5])

In [35]:
#problem7
def func_1(array):
    while np.mean(array)>5:
        for i in range(len(array)):
            array[i]=array[i]/2
    if np.mean(array)<=5:
        print(array)
    
c=np.array([10,6,18,3])
func_1(c)

[5 3 9 1]


In [56]:
#problem8
def func_2(array):
    for i in range(0,4):
        print(array[..., i],"\n")
    
def func_3(array):
    for i in range(0,5):
        print(array[i,...])
    
    
d=np.random.randint(1,10,(5,4))  
print(d,"\n")

func_2(d)
func_3(d)

[[3 6 4 8]
 [6 9 4 4]
 [1 3 6 8]
 [1 8 2 8]
 [8 8 9 3]] 

[3 6 1 1 8] 

[6 9 3 8 8] 

[4 4 6 2 9] 

[8 4 8 8 3] 

[3 6 4 8]
[6 9 4 4]
[1 3 6 8]
[1 8 2 8]
[8 8 9 3]
